name: Node CI Suite

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Node Tests

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    strategy:
      matrix:
        node-version: [22.x]
        os: [sfdc-hk-ubuntu-latest]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
